// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEWDAkulV0DDCTUVwx0Oz5Uo3vYHSzcPw',
    appId: '1:607942952941:web:70280c53a96af20bc589e4',
    messagingSenderId: '607942952941',
    projectId: 'restaurantandorder-edb77',
    authDomain: 'restaurantandorder-edb77.firebaseapp.com',
    storageBucket: 'restaurantandorder-edb77.appspot.com',
    measurementId: 'G-7YJEP8XXFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJeFOQ1OqCzvohVS33zKj5XFqfe59_3jw',
    appId: '1:607942952941:android:af78f866ff382644c589e4',
    messagingSenderId: '607942952941',
    projectId: 'restaurantandorder-edb77',
    storageBucket: 'restaurantandorder-edb77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZCczKGlce4dHQStcCMcb2us2KaaA8p-0',
    appId: '1:607942952941:ios:2e419620b12d1951c589e4',
    messagingSenderId: '607942952941',
    projectId: 'restaurantandorder-edb77',
    storageBucket: 'restaurantandorder-edb77.appspot.com',
    iosBundleId: 'com.example.restaurantAndOrder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZCczKGlce4dHQStcCMcb2us2KaaA8p-0',
    appId: '1:607942952941:ios:345f49df96ab5f19c589e4',
    messagingSenderId: '607942952941',
    projectId: 'restaurantandorder-edb77',
    storageBucket: 'restaurantandorder-edb77.appspot.com',
    iosBundleId: 'com.example.restaurantAndOrder.RunnerTests',
  );
}
